Refactor CI/CD script for Docker deployment

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -60,35 +60,36 @@ jobs:
             key: ${{ secrets.EC2_SSH_KEY }}
             envs: ACCOUNT_ID,REGION
             script: |
-              ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
-              REGION=us-east-1
+               AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
+               REGION=us-east-1
 
-              IMAGE=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/nodejs-app:latest
-              PREV_IMAGE=nodejs-app:previous
+            IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/nodejs-app:latest
+            PREV_IMAGE=nodejs-app:previous
 
-              echo "Pulling latest image..."
-              docker pull $IMAGE
+            echo "Logging into ECR..."
+            aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
 
-              echo "Saving backup image..."
-              docker tag $IMAGE $PREV_IMAGE || true
+            echo "Pulling latest image..."
+            docker pull $IMAGE
 
-              echo "Stopping old container..."
-              docker stop nodejs-app || true
-              docker rm nodejs-app || true
-              echo "Starting new container..."
-              docker run -d --name nodejs-app -p 80:3000 $IMAGE
+            echo "Saving backup image..."
+            docker tag $IMAGE $PREV_IMAGE || true
 
-              echo "Waiting..."
-              sleep 10
+            echo "Stopping old container..."
+            docker stop nodejs-app || true
+            docker rm nodejs-app || true
 
-              echo "Health check..."
-              if curl -f http://localhost:80; then
-                echo "SUCCESS"
-              else
-                echo "FAILED → Rolling back"
+            echo "Starting new container..."
+            docker run -d --name nodejs-app -p 80:3000 $IMAGE
 
-                docker stop nodejs-app || true
-                docker rm nodejs-app || true
-                docker run -d --name nodejs-app -p 80:3000 $PREV_IMAGE
-                exit 1
-              fi
+            echo "Waiting..."
+            sleep 10
+
+            echo "Health check..."
+            if curl -f http://localhost:80; then
+               echo "SUCCESS"
+            else
+               echo "FAILED → Rolling back"
+               docker stop nodejs-app || true
+               docker rm nodejs-app || true
+               docker run -d --name nodejs-app -p 80
